name: user_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.14
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.11
  get: 4.6.1
  http: ^0.13.4
  image_picker: ^0.8.5
  lottie: ^1.2.2
  maps_launcher: 2.0.1
  paginate_firestore: 1.0.3+1
  path: ^1.8.1
  url_launcher: ^6.0.20
  http_auth: 1.0.1
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: assets/images/icon.png
  android: true
  ios: true

flutter:
  assets:
    - assets/images/
    - assets/lottie/

  uses-material-design: true
